---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sample-crd.example.com
  resources:
  - webapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample-crd.example.com
  resources:
  - webapps/finalizers
  verbs:
  - update
- apiGroups:
  - sample-crd.example.com
  resources:
  - webapps/status
  verbs:
  - get
  - patch
  - update
