apiVersion: sample-crd.example.com/v1
kind: WebApp
metadata:
  labels:
    app.kubernetes.io/name: sample-crd
    app.kubernetes.io/managed-by: kustomize
  name: webapp-sample
spec:
  # TODO(user): Add fields here
